//bookmarkActions
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const NEW_BOOKMARK = 'NEW_BOOKMARK';
//loginActions
export const LOGIN = 'LOGIN';
//subscriptionActions
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
export const NEW_SUBSCRIPTION = 'NEW_SUBSCRIPTION';
export const POPULATE_SUBSCRIPTION = 'POPULATE_SUBSCRIPTION';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const CLEAR_STATE = 'CLEAR_STATE';
//navActions
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
export const SET_SUBSCRIPTION_FOCUS = 'SET_SUBSCRIPTION_FOCUS';
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const ARTICLE_FOCUS = 'ARTICLE_FOCUS';
export const ON_FORM_CHANGE = 'ON_FORM_CHANGE';
