export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const NEW_BOOKMARK = 'NEW_BOOKMARK';
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
export const NEW_SUBSCRIPTION = 'NEW_SUBSCRIPTION';
export const LOGIN = 'LOGIN';
